services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /dev/urandom:/dev/random:ro
    environment:
      - SERVICE_FQDN_METABASE_3000=https://rebase.app.t3ai.xyz
      - MB_SITE_NAME=Rebase
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=postgresql
      - MB_DB_PORT=5432
      - MB_DB_DBNAME=${POSTGRESQL_DATABASE:-rebase}
      - MB_DB_USER=${SERVICE_USER_POSTGRESQL}
      - MB_DB_PASS=${SERVICE_PASSWORD_POSTGRESQL}
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://127.0.0.1:3000/api/health || exit 1
      interval: 5s
      timeout: 20s
      retries: 10
    labels:
      - traefik.http.routers.http-rebase.entryPoints=http
      - traefik.http.routers.http-rebase.middlewares=redirect-to-https
      - traefik.http.routers.http-rebase.rule=Host(`rebase.app.t3ai.xyz`) && PathPrefix(`/`)
      - traefik.http.routers.http-rebase.service=http-rebase
      - traefik.http.services.http-rebase.loadbalancer.server.port=3000
      - traefik.http.routers.https-rebase.entryPoints=https
      - traefik.http.routers.https-rebase.middlewares=gzip
      - traefik.http.routers.https-rebase.rule=Host(`rebase.app.t3ai.xyz`) && PathPrefix(`/`)
      - traefik.http.routers.https-rebase.service=https-rebase
      - traefik.http.routers.https-rebase.tls=true
      - traefik.http.routers.https-rebase.tls.certresolver=letsencrypt
      - traefik.http.services.https-rebase.loadbalancer.server.port=3000

  postgresql:
    image: postgres:16-alpine
    volumes:
      - rebase-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRESQL}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}
      - POSTGRES_DB=${POSTGRESQL_DATABASE:-rebase}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  rebase-postgresql-data:
